config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#home_page'

  resources :requests
  resources :users
  resources :stocks
  resources :installments
  resources :discounts
  resources :sales
  resources :items
  resources :products
  resources :addresses
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :client, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
	has_one :address
	has_many :sales
	accepts_nested_attributes_for :address
end

app/models/discount.rb
class Discount < ApplicationRecord
	has_many :sales
	enum kind: [:percentage, :money]
end

app/models/installment.rb
class Installment < ApplicationRecord
  belongs_to :sale
  validates :value, presence: true, numericality: true
  validates :payment_date, presence: true

  after_save do
  	@sale = Sale.find(self.sale)
  	@sale.update_attribute(:remaining, @sale.remaining - self.value)
  end

  before_destroy do
  	@sale = Sale.find(self.sale)
  	@sale.update_attribute(:remaining, @sale.remaining + self.value)
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :product
  belongs_to :sale, optional: true
  validate :has_products?

  before_save do
  	self.total = self.product.price * self.quantity
  	@stock2 = Stock.where(product: self.product)
  	@quantity2 = @stock2.first.quantity
  	@stock2.first.update_attribute(:quantity, @quantity2 - self.quantity)
  end

  def has_products?
  	@stock = Stock.where(product: self.product)
  	@quantity = @stock.first.quantity
  	errors.add(:base, " -- Nao ha estoque disponivel.") if @quantity < self.quantity 
  end

  before_destroy do
  	@stock2 = Stock.where(product: self.product)
  	@quantity2 = @stock2.first.quantity
  	@stock2.first.update_attribute(:quantity, @quantity2 + self.quantity)
  end
end

app/models/product.rb
class Product < ApplicationRecord
	enum status: [:enabled, :disabled]

	# create disabled product
	before_create do
		self.status = :disabled
	end
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :product
  belongs_to :client
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :client
  belongs_to :discount, optional: true
  has_many :items, :dependent => :destroy
  has_many :installments, :dependent => :delete_all
  enum status: [:pending, :paid]
  accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true
  validate :has_items?

  def has_items?
    errors.add(:base, " -- Precisa de ao menos um item.") if self.items.blank?
  end

  before_create do
  	if new_record?
  	  self.status = :pending

      @current_value = 0;
      self.items.each do |item|
        @current_value += item.product.price * item.quantity
      end

      if self.discount.blank?
        self.total = @current_value
      elsif self.discount.kind == 'money'
        self.total = @current_value - self.discount.value
      elsif self.discount.kind == 'percentage'
        self.total = @current_value * (1 - (self.discount.value/100))
      end 

      self.remaining = self.total
  	end
  end

  before_save do
    unless self.remaining.blank?
      if self.remaining <= 0
        self.remaining = 0
        self.status = :paid
      else
        self.status = :pending
      end
    end
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
  validates :product, uniqueness: true

  # atualizar total
  before_save do
  	@product = Product.find(self.product)
  	self.total = self.quantity * @product.price
  end

  # atualizar status do produto 
  after_save do
  	@product = Product.find(self.product)
  	if self.quantity == 0
  		@product.update_attribute(:status, :disabled)
  	else
  		@product.update_attribute(:status, :enabled)
	end
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:product_id, :quantity, :total)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/stocks/_form.html.erb
<%= form_for @stock, :html => { :class => "form-horizontal stock" } do |f| %>

  <% if @stock.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @stock.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :product_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select(:product_id, Product.all.collect { |p|
    [p.name, p.id] }, {include_blank: 'Selecione...'}, {class: "form-control"}) %>
    </div>
    <%=f.error_span(:product_id) %>
  </div>
  <div class="form-group">
    <%= f.label :quantity, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :quantity, min: 0, :class => 'form-control' %>
    </div>
    <%=f.error_span(:quantity) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                stocks_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/stocks/edit.html.erb
<%- model_class = Stock -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stocks/index.html.erb
<%- model_class = Stock -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:product_id) %></th>
      <th><%= model_class.human_attribute_name(:quantity) %></th>
      <th><%= model_class.human_attribute_name(:total) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= link_to stock.id, stock_path(stock) %></td>
        <td><%= link_to stock.product.name, product_path(stock.product) %></td>
        <td><%= stock.quantity %></td>
        <td><%= number_with_precision(stock.total, precision:2) %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
              stock_path(stock), :class => 'btn btn-default btn-xs'  %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_stock_path(stock), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      stock_path(stock),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_stock_path,
            :class => 'btn btn-primary' %>

app/views/stocks/new.html.erb
<%- model_class = Stock -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stocks/show.html.erb
<%- model_class = Stock -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:product_id) %>:</strong></dt>
  <dd><%= link_to @stock.product.name, product_path(@stock.product) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quantity) %>:</strong></dt>
  <dd><%= @stock.quantity %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total) %>:</strong></dt>
  <dd><%= number_with_precision(@stock.total, precision: 2) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created_at) %>:</strong></dt>
  <dd><%= @stock.created_at %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              stocks_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_stock_path(@stock), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              stock_path(@stock),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>