config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#home_page'

  resources :requests
  resources :users
  resources :stocks
  resources :installments
  resources :discounts
  resources :sales
  resources :items
  resources :products
  resources :addresses
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :client, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
	has_one :address
	has_many :sales
	accepts_nested_attributes_for :address
end

app/models/discount.rb
class Discount < ApplicationRecord
	has_many :sales
	enum kind: [:percentage, :money]
end

app/models/installment.rb
class Installment < ApplicationRecord
  belongs_to :sale
  validates :value, presence: true, numericality: true
  validates :payment_date, presence: true

  after_save do
  	@sale = Sale.find(self.sale)
  	@sale.update_attribute(:remaining, @sale.remaining - self.value)
  end

  before_destroy do
  	@sale = Sale.find(self.sale)
  	@sale.update_attribute(:remaining, @sale.remaining + self.value)
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :product
  belongs_to :sale, optional: true
  validate :has_products?

  before_save do
  	self.total = self.product.price * self.quantity
  	@stock2 = Stock.where(product: self.product)
  	@quantity2 = @stock2.first.quantity
  	@stock2.first.update_attribute(:quantity, @quantity2 - self.quantity)
  end

  def has_products?
  	@stock = Stock.where(product: self.product)
  	@quantity = @stock.first.quantity
  	errors.add(:base, " -- Nao ha estoque disponivel.") if @quantity < self.quantity 
  end

  before_destroy do
  	@stock2 = Stock.where(product: self.product)
  	@quantity2 = @stock2.first.quantity
  	@stock2.first.update_attribute(:quantity, @quantity2 + self.quantity)
  end
end

app/models/product.rb
class Product < ApplicationRecord
	enum status: [:enabled, :disabled]

	# create disabled product
	before_create do
		self.status = :disabled
	end
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :product
  belongs_to :client
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :client
  belongs_to :discount, optional: true
  has_many :items, :dependent => :destroy
  has_many :installments, :dependent => :delete_all
  enum status: [:pending, :paid]
  accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true
  validate :has_items?

  def has_items?
    errors.add(:base, " -- Precisa de ao menos um item.") if self.items.blank?
  end

  before_create do
  	if new_record?
  	  self.status = :pending

      @current_value = 0;
      self.items.each do |item|
        @current_value += item.product.price * item.quantity
      end

      if self.discount.blank?
        self.total = @current_value
      elsif self.discount.kind == 'money'
        self.total = @current_value - self.discount.value
      elsif self.discount.kind == 'percentage'
        self.total = @current_value * (1 - (self.discount.value/100))
      end 

      self.remaining = self.total
  	end
  end

  before_save do
    unless self.remaining.blank?
      if self.remaining <= 0
        self.remaining = 0
        self.status = :paid
      else
        self.status = :pending
      end
    end
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
  validates :product, uniqueness: true

  # atualizar total
  before_save do
  	@product = Product.find(self.product)
  	self.total = self.quantity * @product.price
  end

  # atualizar status do produto 
  after_save do
  	@product = Product.find(self.product)
  	if self.quantity == 0
  		@product.update_attribute(:status, :disabled)
  	else
  		@product.update_attribute(:status, :enabled)
	end
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    @sale.items.each do |item|
      item.new
    end
  end

  # GET /sales/1/edit
  def edit
    unless @sale.items
      @sale.items.each do |item|
        item.new
      end
    end
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:client_id, :sale_date, :total, :remaining, :status, :discount_id, 
        :items_attributes => [:product_id, :sale_id, :quantity, :total, :_destroy])
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sales/_form.html.erb
<%= form_for @sale, :html => { :class => "form-horizontal sale" } do |f| %>

  <% if @sale.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @sale.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :client_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select(:client_id, Client.all.collect { |c|
    [c.name, c.id] }, {include_blank: 'Selecione...'}, {class: "form-control"}) %>
    </div>
    <%=f.error_span(:client_id) %>
  </div>

  <div class="form-group">
    <%= f.label :sale_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_select :sale_date %>
    </div>
    <%=f.error_span(:sale_date) %>
  </div>
  <div class="form-group">
    <%= f.label :discount_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select(:discount_id, Discount.all.collect { |d|
    [d.name, d.id] }, {include_blank: 'Selecione...'}, {class: "form-control"}) %>
    </div>
    <%=f.error_span(:discount_id) %>
  </div>

  <%= link_to_add_association 'Adicionar Item', f, :items,
    'data-association-insertion-node' => "#item ol",
    'data-association-insertion-method' => "append" %>

  <hr/>

  <div class="form-group">
    <fieldset id="item">
      <ol>
        <%= f.fields_for :items do |item| %>
          <%= render partial: "item_fields", locals: {f: item} %>
        <% end %>
      </ol>
    </fieldset>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sales_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/sales/_item_fields.html.erb
<div class="form-group">
  <li class="control-group nested-fields"> 
    <div class="controls"> 
      <div class="form-group">
        <%= f.label :product_id, :class => 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= f.select(:product_id, Product.all.collect { |p|
        [p.name, p.id] }, {include_blank: 'Selecione...'}, {class: "form-control"}) %>
        </div>
        <%=f.error_span(:product_id) %>
      </div>

      <div class="form-group">
        <%= f.label :quantity, :class => 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= f.number_field :quantity, min: 1, :class => 'form-control' %>
        </div>
        <%=f.error_span(:quantity) %>

        <%= link_to_remove_association "Remover Item", f %>
      </div>
    </div>
  </li>
</div>

app/views/sales/edit.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sales/index.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:client_id) %></th>
      <th><%= model_class.human_attribute_name(:sale_date) %></th>
      <th><%= model_class.human_attribute_name(:discount_id) %></th>
      <th><%= model_class.human_attribute_name(:total) %></th>
      <th><%= model_class.human_attribute_name(:remaining) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= link_to sale.id, sale_path(sale) %></td>
        <td><%= link_to sale.client.name, client_path(sale.client) %></td>
        <td><%= sale.sale_date %></td>
        <% if sale.discount.blank? %>
          <td><%= '-' %></td>
        <% else %>
          <td><%= link_to sale.discount.name, discount_path(sale.discount) %></td>
        <% end %>
        <td><%= number_with_precision(sale.total, precision: 2) %></td>
        <td><%= number_with_precision(sale.remaining, precision: 2) %></td>
        <td><%= sale.status %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
              sale_path(sale), :class => 'btn btn-default btn-xs'  %>
          <% if sale.remaining > 0 %>
            <%= link_to 'Pagamento', new_installment_path, :class => 'btn btn-default btn-xs'  %>
          <% end %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sale_path(sale),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sale_path,
            :class => 'btn btn-primary' %>

app/views/sales/new.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sales/show.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:client_id) %>:</strong></dt>
  <dd><%= link_to @sale.client.name, client_path(@sale.client) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sale_date) %>:</strong></dt>
  <dd><%= @sale.sale_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:discount_id) %>:</strong></dt>
  <% if @sale.discount.blank? %>
    <dd><%= '-' %></dd>
  <% else %>
    <dd><%= link_to @sale.discount.name, discount_path(@sale.discount) %></dd>
  <% end %>
  <dt><strong><%= model_class.human_attribute_name(:total) %>:</strong></dt>
  <dd><%= number_with_precision(@sale.total, precision: 2) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remaining) %>:</strong></dt>
  <dd><%= number_with_precision(@sale.remaining, precision: 2) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @sale.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created_at) %>:</strong></dt>
  <dd><%= @sale.created_at %></dd>
  <br>
  <dt><strong><%= model_class.human_attribute_name('Itens') %>:</strong></dt>
  <% @sale.items.each do |item| %>  
    <dd>Product: <%= link_to item.product.name, product_path(item.product) %> -- Quantity: <%= item.quantity %></dd>
  <% end %>
  <dd></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              sales_path, :class => 'btn btn-default'  %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sale_path(@sale),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>