config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#home_page'

  resources :requests
  resources :users
  resources :stocks
  resources :installments
  resources :discounts
  resources :sales
  resources :items
  resources :products
  resources :addresses
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :client, optional: true
end

app/models/client.rb
class Client < ApplicationRecord
	has_one :address
	has_many :sales
	accepts_nested_attributes_for :address
end

app/models/discount.rb
class Discount < ApplicationRecord
	has_many :sales
	enum kind: [:percentage, :money]
end

app/models/installment.rb
class Installment < ApplicationRecord
  belongs_to :sale
  validates :value, presence: true, numericality: true
  validates :payment_date, presence: true

  after_save do
  	@sale = Sale.find(self.sale)
  	@sale.update_attribute(:remaining, @sale.remaining - self.value)
  end

  before_destroy do
  	@sale = Sale.find(self.sale)
  	@sale.update_attribute(:remaining, @sale.remaining + self.value)
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :product
  belongs_to :sale, optional: true
  validate :has_products?

  before_save do
  	self.total = self.product.price * self.quantity
  	@stock2 = Stock.where(product: self.product)
  	@quantity2 = @stock2.first.quantity
  	@stock2.first.update_attribute(:quantity, @quantity2 - self.quantity)
  end

  def has_products?
  	@stock = Stock.where(product: self.product)
  	@quantity = @stock.first.quantity
  	errors.add(:base, " -- Nao ha estoque disponivel.") if @quantity < self.quantity 
  end

  before_destroy do
  	@stock2 = Stock.where(product: self.product)
  	@quantity2 = @stock2.first.quantity
  	@stock2.first.update_attribute(:quantity, @quantity2 + self.quantity)
  end
end

app/models/product.rb
class Product < ApplicationRecord
	enum status: [:enabled, :disabled]

	# create disabled product
	before_create do
		self.status = :disabled
	end
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :product
  belongs_to :client
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :client
  belongs_to :discount, optional: true
  has_many :items, :dependent => :destroy
  has_many :installments, :dependent => :delete_all
  enum status: [:pending, :paid]
  accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true
  validate :has_items?

  def has_items?
    errors.add(:base, " -- Precisa de ao menos um item.") if self.items.blank?
  end

  before_create do
  	if new_record?
  	  self.status = :pending

      @current_value = 0;
      self.items.each do |item|
        @current_value += item.product.price * item.quantity
      end

      if self.discount.blank?
        self.total = @current_value
      elsif self.discount.kind == 'money'
        self.total = @current_value - self.discount.value
      elsif self.discount.kind == 'percentage'
        self.total = @current_value * (1 - (self.discount.value/100))
      end 

      self.remaining = self.total
  	end
  end

  before_save do
    unless self.remaining.blank?
      if self.remaining <= 0
        self.remaining = 0
        self.status = :paid
      else
        self.status = :pending
      end
    end
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
  validates :product, uniqueness: true

  # atualizar total
  before_save do
  	@product = Product.find(self.product)
  	self.total = self.quantity * @product.price
  end

  # atualizar status do produto 
  after_save do
  	@product = Product.find(self.product)
  	if self.quantity == 0
  		@product.update_attribute(:status, :disabled)
  	else
  		@product.update_attribute(:status, :enabled)
	end
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AdmSystem" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-fixed-top">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">AdmSystem</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Clients", clients_path  %></li>
            <li><%= link_to "Sales", sales_path  %></li>
            <li><%= link_to "Installments", installments_path  %></li>
          </ul>
        </div>
    </div>

      <div class="row">
        <div class="col-lg-2">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li><%= link_to "Clients", clients_path  %></li>
              <li><%= link_to "Addresses", addresses_path  %></li>
            <li><%= link_to "Sales", sales_path  %></li>
            <li><%= link_to "Installments", installments_path  %></li>
            <li><%= link_to "Products", products_path  %></li>
            <li><%= link_to "Stocks", stocks_path  %></li>
            <li><%= link_to "Items", items_path  %></li>
            <li><%= link_to "Discounts", discounts_path  %></li>
            <li><%= link_to "Requests", requests_path  %></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-8">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

  </body>
</html>